### ISSUE TITLE
Метрополитен 1

### ISSUE THREAD

**Issue by OstaninaTatiana** [OstaninaTatiana/Academy#1]
@vdetstvepil 
Коммит метрополитен 1 (могу утром начать делать дальше)

**Comment by vdetstvepil** [comment]
25 строка в классе Station.cs. Я объяснял на 11ом занятии, почему так нельзя делать, идет присвоение ссылок, а нужен копипастинг.

**Comment by vdetstvepil** [comment]
Принято авансом, жду исправлений

**Comment by OstaninaTatiana** [comment]
Спасибо, исправила

**Comment by vdetstvepil** [comment]
Принято.
